### ISSUE TITLE
locale setting

### ISSUE THREAD

**Issue by drmarwat** [guille/dotfiles#1]
Hello ,
I successfully installed-used your dot files and I am loving the setup
One issue is bit bothering
Locale changes back to es even that I set system locale to en . How can I keep locale on en than on es permanently

**Comment by guille** [comment]
Glad to hear that @drmarwat!

The offending lines are 106-107 in the `install` script:

```bash
infoprint "Setting spanish keyboard"
localectl set-x11-keymap es
```

You can execute that command with your preferred locale and it should override the changes.

**Comment by drmarwat** [comment]
Thanks , Thats what I did and it resolved the issue.

When i Login to i3 I get all these terminals open by default
https://ibb.co/NN5Jrqb
Can I edit some settings in config so that I have only terminator open ?
