### ISSUE TITLE
multiple windows open

### ISSUE THREAD

**Issue by drmarwat** [guille/dotfiles#2]
When i Login to i3 I get all these terminals and windows open by default
https://ibb.co/NN5Jrqb
Can I edit some settings in config so that I have only terminator open ?

**Comment by guille** [comment]
Yes, look at the line 227 in `dots/i3`:

```bash
exec --no-startup-id i3-msg "workspace $ws2; append_layout ~/.config/i3/dev.json; exec subl; exec i3-sensible-terminal; exec i3-sensible-terminal"
```

I recommend becoming familiar with the i3 windows manager. You can find its documentation of layout saving [here](https://i3wm.org/docs/layout-saving.html)
